{
  "records": [
  {
    "Position": 273,
    "CMutation": "c.818G>A",
    "AAMutation": "p.R273H",
    "CosmicID": 10660,
    "Count": 40,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "1. APR-246+Cisplatin,  Approach:p53 Activator, Evidence: Actionable",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 273,
    "CMutation": "c.818G>T",
    "AAMutation": "p.R273L",
    "CosmicID": 10779,
    "Count": 13,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 157,
    "CMutation": "c.469G>T",
    "AAMutation": "p.V157F",
    "CosmicID": 10670,
    "Count": 10,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 220,
    "CMutation": "c.?",
    "AAMutation": "p.Y220C",
    "CosmicID": 96438,
    "Count": 8,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "1. Seliciclib, Approach: n/a, Evidence: Actionable",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 245,
    "CMutation": "c.733G>T",
    "AAMutation": "p.G245C",
    "CosmicID": 11081,
    "Count": 7,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 249,
    "CMutation": "c.745A>T",
    "AAMutation": "p.R249W",
    "CosmicID": 43629,
    "Count": 6,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 132,
    "CMutation": "c.396G>T",
    "AAMutation": "p.K132N",
    "CosmicID": 10991,
    "Count": 6,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 252,
    "CMutation": "c.754C>T",
    "AAMutation": "p.L252F",
    "CosmicID": 44054,
    "Count": 6,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 163,
    "CMutation": "c.488A>G",
    "AAMutation": "p.Y163C",
    "CosmicID": 10808,
    "Count": 6,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 254,
    "CMutation": "c.760A>T",
    "AAMutation": "p.I254F",
    "CosmicID": 45647,
    "Count": 6,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 248,
    "CMutation": "c.743G>A",
    "AAMutation": "p.R248Q",
    "CosmicID": 10662,
    "Count": 6,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 154,
    "CMutation": "c.461G>T",
    "AAMutation": "p.G154V",
    "CosmicID": 6815,
    "Count": 5,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 273,
    "CMutation": "c.?",
    "AAMutation": "p.R273L",
    "CosmicID": 144153,
    "Count": 4,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 248,
    "CMutation": "c.743G>T",
    "AAMutation": "p.R248L",
    "CosmicID": 6549,
    "Count": 4,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 248,
    "CMutation": "c.742C>T",
    "AAMutation": "p.R248W",
    "CosmicID": 10656,
    "Count": 4,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "1. APR-246+Cisplatin,  Approach:p53 Activator, Evidence: Actionable",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 220,
    "CMutation": "c.659A>G",
    "AAMutation": "p.Y220C",
    "CosmicID": 10758,
    "Count": 4,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "1. Seliciclib, Approach: n/a, Evidence: Actionable",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 249,
    "CMutation": "c.747G>T",
    "AAMutation": "p.R249S",
    "CosmicID": 10817,
    "Count": 4,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 158,
    "CMutation": "c.473G>T",
    "AAMutation": "p.R158L",
    "CosmicID": 10714,
    "Count": 3,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 159,
    "CMutation": "c.476C>T",
    "AAMutation": "p.A159V",
    "CosmicID": 11148,
    "Count": 3,
    "Type": "Substitution - Missense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  },
  {
    "Position": 62,
    "CMutation": "c.184G>T",
    "AAMutation": "p.E62*",
    "CosmicID": 10827,
    "Count": 3,
    "Type": "Substitution - Nonsense",
    "": "",
    "Sensitive": "",
    "Resistant": "",
    "Predicted-Resistant": "",
    "Predicted-Sensitive": "",
    "Decreased Response": ""
  }
]
}
